### ISSUE TITLE
Setup Kanban Board

### ISSUE THREAD

**Issue by rachidelaid** [rachidelaid/billionaire-appointment-back-end#1]
This project consists of an app where you can schedule an appointment with a billionaire.
We are going to use two stand-alone apps:
- Back-end: Rails API
- Front-end: ReactJS/Redux

front-end repo: https://github.com/rachidelaid/billionaire-appointment-front-end

The team responsible for this project is made of four members: 
@rachidelaid 
@matovu-farid 
@guerreiropedr0 
@orozCoding 

Kanban board screenshot:
![image](https://user-images.githubusercontent.com/42470159/171405547-f53281ec-4cdb-4f73-bb58-a72740bb1f47.png)

**Comment by MuriloRoque** [comment]
Hi @rachidelaid, @matovu-farid, @guerreiropedr0, @orozCoding,

Good job so far!
There are some issues that you still need to work on but you are almost there!

## Suggested changes

- [x] Please put a screenshot of your Kanban board in this issue's description, just like it's mentioned in [the requirements](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md).

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by MuriloRoque** [comment]
Hi @rachidelaid, @matovu-farid, @guerreiropedr0, @orozCoding,

In my opinion, your project is complete!

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
